name: "Upload Any Mod on Change"

on:
  push:
    branches:
      - main
    paths:
      - 'Gamemode Mods/**'
      - 'Utility Mods/**'
      - 'Weapon Mods/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract Workshop ID from modinfo.sbmi
        id: getid
        run: |
          # Find the modinfo.sbmi files in all mod folders
          sbmi_files=$(find "${{ github.workspace }}" -name 'modinfo.sbmi')

          # Extract Workshop IDs
          for sbmi_file in $sbmi_files; do
            workshop_id=$(grep 'WorkshopID' "$sbmi_file" | cut -d ':' -f2 | xargs)
            if [ -n "$workshop_id" ]; then
              echo "::set-output name=WORKSHOP_ID::$workshop_id"
              break  # Stop after finding the first valid Workshop ID
            fi
          done

      - uses: AnarkisGaming/workshop@v1
        if: steps.getid.outputs.WORKSHOP_ID
        with:
          appID: 244850
          publishedFileID: ${{ steps.getid.outputs.WORKSHOP_ID }}
          path: "${{ github.workspace }}"
          changelog: ${{ github.event.head_commit.message }}
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.STEAM_ACCOUNT_NAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
