name: "Upload Any Mod on Change"

on:
  push:
    branches:
      - main
    paths:
      - 'Gamemode Mods/**'
      - 'Utility Mods/**'
      - 'Weapon Mods/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Find changed Mod directories
        id: findmod
        run: |
          # Using git diff to find all directories that contain changed modinfo.sbmi files
          MOD_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'modinfo.sbmi' | sed -E 's|/[^/]+$||' | sort -u)
          echo "Mod directories with changes: $MOD_DIRS"
          echo "::set-output name=MOD_DIRS::${MOD_DIRS}"

      - name: Upload mods to Steam Workshop
        id: upload
        run: |
          IFS=$'\n'
          for MOD_DIR in ${{ steps.findmod.outputs.MOD_DIRS }}
          do
            WORKSHOP_ID=$(grep 'WorkshopID' "${{ github.workspace }}/${MOD_DIR}/modinfo.sbmi" | cut -d ':' -f2 | xargs)
            if [ -n "$WORKSHOP_ID" ]; then
              echo "Uploading Mod Directory: $MOD_DIR with Workshop ID: $WORKSHOP_ID"
              AnarkisGaming/workshop@v1 with:
                appID: 244850
                publishedFileID: $WORKSHOP_ID
                path: ${{ github.workspace }}/$MOD_DIR
                changelog: ${{ github.event.head_commit.message }}
              env:
                STEAM_ACCOUNT_NAME: ${{ secrets.STEAM_ACCOUNT_NAME }}
                STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
            fi
          done
