name: "Upload Any Mod on Change"

on:
  push:
    branches:
      - main
    paths:
      - 'Gamemode Mods/**'
      - 'Utility Mods/**'
      - 'Weapon Mods/**'

jobs:
  find-mod-directory:
    runs-on: ubuntu-latest
    outputs:
      mod_dir: ${{ steps.set_mod_dir.outputs.mod_dir }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Find changed Mod directory
        id: set_mod_dir
        run: |
          MOD_DIR=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'modinfo.sbmi' | sed -E 's|/[^/]+$||' | head -n 1)
          echo "Mod directory with changes: $MOD_DIR"
          echo "mod_dir=$MOD_DIR" >> $GITHUB_ENV

      - name: Extract Workshop ID
        if: env.mod_dir
        run: |
          WORKSHOP_ID=$(grep 'WorkshopID' "${{ github.workspace }}/${{ env.mod_dir }}/modinfo.sbmi" | cut -d ':' -f2 | xargs)
          echo "Extracted Workshop ID: $WORKSHOP_ID"
          echo "workshop_id=$WORKSHOP_ID" >> $GITHUB_ENV
